$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bubble-wrap'      # Thanks Matt!

Motion::Project::App.setup do |app|
  app.name         = 'DataMart'
  app.frameworks  += ['CoreData']
  app.icons        = ['db.png']
end