$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bubble-wrap'

Motion::Project::App.setup do |app|
  app.name        = 'SvcData'
  app.frameworks += ['CoreData']
  app.sdk_version = '5.1'
  app.icons       = ['database.png']
end
